@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
    LifeLineBackgroundColor grey
}

autonumber
autoActivate on

participant "nsq 表记录创建" as insert
participant "retail-sales" as sales
participant "DB" as db
participant "ES" as es

insert ->o sales : insert 消息
sales -> db : 查询表记录
return 返回
sales -> es : 同步 ES
return 返回
return 返回

@enduml