@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox

'使用 toy 主题


'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 1

' 皮肤
skinparam sequence {
    ParticipantBackgroundColor #white
       ParticipantFontColor black
       ActorBackgroundColor white
       ActorFontColor black
}

actor 服务商或家装小二 as admin
participant xp as xp
participant ConsultationOrderWriteService as ConsultationOrderWriteService
participant ConsultationOrderDomainService as ConsultationOrderDomainService
participant ConsultationAbilityDomainService as ConsultationAbilityDomainService
participant ConsultationRuleDomainService as ConsultationRuleDomainService
participant ConsultationOrderRepository as ConsultationOrderRepository


admin --> xp : 调用 top 响应
activate xp

xp --> ConsultationOrderWriteService : 响应
activate ConsultationOrderWriteService

ConsultationOrderWriteService -> ConsultationOrderWriteService : 参数校验，是否已响应过，响应方案
activate ConsultationOrderWriteService
return

ConsultationOrderWriteService -> ConsultationOrderDomainService : 响应
activate ConsultationOrderDomainService

ConsultationOrderDomainService -> ConsultationAbilityDomainService : 校验角色能力

ConsultationOrderDomainService -> ConsultationOrderRepository : 持久化
activate ConsultationOrderRepository

return
return
return
return






@enduml