@startuml
'https://plantuml.com/state-diagram
!theme toy

hide footbox
skinparam backgroundColor #EEEBDC

skinparam sequence {
    LifeLineBackgroundColor grey
}

state "创建中" as creating
creating : 只能流转到生效中
creating : 可以流转到被删除

state "生效中" as running
running : 可以流转到修改中
running : 可以流转到被删除
running : 是修改的准入条件，活动必须生效才可以进行修改
running : 可以由创建、修改流转到此状态

state "修改中" as updating
updating : 可以流转到生效中
updating : 可以流转到被删除

state "被删除" as deleted
deleted : 被删除是一个单独的字段，不与其他状态共享同一个字段

creating -right-> running

running -right-> updating

updating -right-> running

creating -----up[dotted]-> deleted

running -----up[dotted]-> deleted

updating -----up[dotted]-> deleted

@enduml