@startuml
skinparam sequenceArrowThickness 1
skinparam roundcorner 20
skinparam maxmessagesize 500
/'skinparam sequenceParticipant underline'/

actor user as u
note left of u
 PC 收银
end note

participant "retail-trade-cart" as cart
participant "retail-trade-cal" as cal
participant "retail-ump" as ump
participant "js" as js
participant "retail-trade-core" as core

u -> cart : 1添加商品
activate cart
cart -> cart : 1.1内部处理
note left
    购物车
        查询
        更新
        保存
end note
return 1.2返回

u -> cart : 2查询购物车列表
activate cart
cart -> cart : 2.1查询购物车

cart -> cart : 2.2商品及库存信息填充

cart -> cal : 2.3计价
activate cal

cal -> ump : 2.4查询商品对应套餐
activate ump
return 2.4.1返回

cal -> js : 2.5最优计算
activate js
return 2.5.1返回

return 2.6返回

return 2.7返回

u -> core : 3支付开单
activate core
return 3.1返回

@enduml