@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox

'使用 toy 主题
!theme toy


'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 2.5

' 皮肤
skinparam sequence {
    LifeLineBackgroundColor #6FC8F2
    ParticipantBackgroundColor #6FC8F2
    ParticipantFontColor black
    ActorBackgroundColor #6FC8F2
    ActorFontColor black
}

actor 小二 as user
participant 工作台 as ws
participant 行业 as industry
participant 供应链平台 as supply

user -> ws : 修改服务内容
activate ws

ws -> industry : （传 ServiceCode）更新：服务分组、名称、类目、管理员、黑白名单信息
activate industry

industry -> supply : 更新写入服务相关信息
activate supply
return 返回

industry -> industry : 更新管理相关信息，并保存 SSC_SupplyServiceCode
return

return


@enduml