@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox

'使用 toy 主题
!theme toy


'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 2.5

' 皮肤
skinparam sequence {
    LifeLineBackgroundColor #6FC8F2
    ParticipantBackgroundColor #6FC8F2
    ParticipantFontColor black
    ActorBackgroundColor #6FC8F2
    ActorFontColor black
}

actor 小二 as user
participant 工作台 as ws
participant 行业 as industry
participant 供应链平台 as supply

user -> ws : 查询服务内容
activate ws

ws -> industry : 带查询条件查询服务内容列表
activate industry

industry -> industry : 参数校验

industry -> supply : 条件查询列表
activate supply
return 返回服务内容列表

return

return


user -> ws : 查询服务详情
activate ws

ws -> industry : 带查询条件 ServiceCode查询服务内容列表
activate industry

industry -> supply : 使用 ServiceCode 查询服务详情
activate supply
return 返回数据

return

return

@enduml