@startuml
'https://plantuml.com/use-case-diagram

left to right direction

'-----------------------------------------------------------
actor 用户 as user
'-----------------------------------------------------------
usecase 配置查询
usecase 根据门店名称查询
usecase 根据门店编号查询
usecase 无筛选条件查询

package 内容 {
    usecase 门店名称
    usecase 门店编号
    usecase 所属tp组织
    usecase tp组织编号
    usecase 门店pos收银方式
}

user --> 配置查询
配置查询 --> 根据门店名称查询
配置查询 --> 根据门店编号查询
配置查询 --> 无筛选条件查询

根据门店名称查询 --> 内容
根据门店编号查询 --> 内容
无筛选条件查询 --> 内容

'-----------------------------------------------------------
usecase 配置编辑
usecase 编辑线上支付方式
usecase 编辑线下支付方式
usecase 默认支付方式

usecase 支付宝扫码
usecase 微信扫码

usecase 现金
usecase 银联
usecase 校园卡
usecase 礼券

usecase 首个选择的支付方式

user --> 配置编辑
配置编辑 --> 编辑线上支付方式
配置编辑 --> 编辑线下支付方式
配置编辑 --> 默认支付方式

编辑线上支付方式 --> 支付宝扫码
编辑线上支付方式 --> 微信扫码

编辑线下支付方式 --> 现金
编辑线下支付方式 --> 银联
编辑线下支付方式 --> 校园卡
编辑线下支付方式 --> 礼券

默认支付方式 --> 首个选择的支付方式
'-----------------------------------------------------------
usecase 配置保存

user --> 配置保存
'-----------------------------------------------------------
@enduml