@startmindmap
'https://plantuml.com/mindmap-diagram
skinparam backgroundColor #EEEBDC

'使用 toy 主题
!theme toy

* 提效3.0 - 增加机审能力

** 异步机审
*** 关键信息提取功能增强
**** 有效期增加时间约束 【当前年 <= 有效期 <= 当前年+5】
**** 录取通知书类型时间约束【当前年份-学制 <= 当前年 <= 当前年份+学制】
**** 增加通用时间识别【识别：发证日期，入学时间，入校时间，入校年月，有效期，有效期限，有效日期】
**** 增加学号识别【识别：学号】




** C 端资料提交
*** 待下次方案补充




** B 端运营侧
*** 增加新页面【直接复制老页面即可，不复用最早老页面】
*** 更换流程发起人【原：张沛，新：？】






@endmindmap
