@startuml

left to right direction

usecase 新建活动 as activity

usecase 活动名称 as name
usecase 活动时间 as duration
usecase 生效时间 as validDuration
usecase 每周生效限制 as weekValidDuration
usecase 促销部门 as department
usecase 促销说明 as mark

activity --> name
activity --> duration
activity --> validDuration
activity --> weekValidDuration
activity --> department
activity --> mark

@enduml