@startuml
actor cart as c

participant "ump-cal" as cal
participant "repo" as repo
participant "promotion-cal" as pcal

c -> cal : 1.计算
note left
    只携带了用户 id
    店铺 id
    需要进行哪种营销活动的计算（打包一口价，限时折扣等）
    商品基本信息
end note
activate cal

cal -> cal : 2.校验
note left
    校验店铺
    校验商品列表是否为空
end note


cal -> cal : 3.initContext
note left
   no efficient content
end note

cal -> cal : 4.prepareData
note left
    此处主要是准备所有可能的优惠活动并填入 context
    较为复杂
end note
activate cal

cal -> repo : 4.1.获取营销活动信息
activate repo
return 4.1.1返回
return

cal -> cal : 5.组装js计算参数并进行计算
activate cal
cal -> pcal : 5.1.js计算优惠
activate pcal
return 5.2返回
return

cal -> cal : 6.组装输出结果
return 7.返回
@enduml