@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox
autoActivate on

'使用 toy 主题
!theme toy

'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 2.5

' 皮肤
skinparam sequence {
    LifeLineBackgroundColor #6FC8F2
    ParticipantBackgroundColor #6FC8F2
    ParticipantFontColor black
    ActorBackgroundColor #6FC8F2
    ActorFontColor black
}

actor 用户 as user
participant UserWriteService as UserWriteService
participant UserConvert as UserConvert
participant StudentAuthenticateDomainService as StudentAuthenticateDomainService
participant UserAuthenticateValidator as UserAuthenticateValidator
participant UserStudentFactory as UserStudentFactory
participant OcrManager as OcrManager
database UserRepository as UserRepository
database ManualAuthSystem as ManualAuthSystem

user -> UserWriteService : 人工审核认证


UserWriteService -> UserWriteService : 参数校验
return

UserWriteService -> UserConvert : 转换人工审核认证请求 UserManualAuthRequest
return

group Distribute Lock
    UserWriteService -> StudentAuthenticateDomainService : 进行人工审核认证/提交
    StudentAuthenticateDomainService -> UserRepository : 查询用户，获取 UserEntity
    return

    StudentAuthenticateDomainService -> UserAuthenticateValidator : 验证当前状态是否能够进行认证
    return

    StudentAuthenticateDomainService -> UserStudentFactory : 组装认证模型
    return

    StudentAuthenticateDomainService -> OcrManager : 资料预审
    return 返回预审结果

    StudentAuthenticateDomainService -> StudentAuthenticateDomainService : 预审成功/失败调用

    alt
        StudentAuthenticateDomainService -> StudentAuthenticateDomainService : 预审成功
        StudentAuthenticateDomainService -> UserRepository : 修改状态
        return
        StudentAuthenticateDomainService -> ManualAuthSystem : 提交到人工审核系统
        return
        return
    end alt

    alt
        StudentAuthenticateDomainService -> StudentAuthenticateDomainService : 认证失败
        StudentAuthenticateDomainService -> UserRepository : 修改状态
        return
        return
    end alt
    return

end group

return
return




@enduml