@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox

'使用 toy 主题


'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 1

' 皮肤
skinparam sequence {
    ParticipantBackgroundColor #white
       ParticipantFontColor black
       ActorBackgroundColor white
       ActorFontColor black
}

actor 小二 as admin
participant RedLineDecideWriteService as RedLineDecideWriteService
participant Metaq as Metaq
participant RedLineDecideFinishHandler as RedLineDecideFinishHandler
participant RedLineRepository as RedLineRepository


RedLineDecideWriteService -> RedLineDecideFinishHandler : 处理投诉判责

activate RedLineDecideFinishHandler

group Transaction
    RedLineDecideFinishHandler -> RedLineRepository : 插入明细（本考核周期）
    RedLineDecideFinishHandler -> RedLineRepository : 汇总明细（本考核周期）
end group

return






@enduml