@startmindmap

skinparam backgroundColor #EEEBDC

skinparam sequence {
    LifeLineBackgroundColor grey
}


* 免费导购业绩

** 数据生成
*** 导购订单生成
*** 业绩订单生成
*** 提成订单生成
*** 邀请奖励订单生成

** 数据更新
*** 导购订单退款
*** 重新计算提成和业绩
*** 邀请奖励提成重新计算
*** 导购订单完成

** 业绩查询

*** 订单列表
**** 隐藏 业绩类型[默认销售业绩]
**** 隐藏 提成类型[免费导购不会生成提成订单]
**** 隐藏 提成金额[免费导购不会生成提成订单]
**** 隐藏 所属部门
**** 隐藏 订单来源[默认全 POS]

*** 导购员明细
**** 隐藏 部门
**** 隐藏 等级
**** 隐藏 累计提成
**** 隐藏 累计邀请奖励
**** 隐藏 累计邀请数

*** 店铺报表
**** 隐藏 提成总额
**** 隐藏 提成订单数
**** 隐藏 提成导购数
**** 前端隐藏 操作按钮[包括：查看提成明细，导出报表]

*** 订单导出
**** 和订单列表保持一致[隐藏字段设置为空]


** 业绩统计
*** 按照销售员维度统计
*** 去掉按照店铺维度统计[发现是免费导购，不去触发店铺统计行为]


@endmindmap