@startuml
actor mobile as m

participant "retail-ump" as ump
participant "ru_activity" as r
participant "ru_activity_item_join" as rij

m -> ump : 1 请求查询8种营销活动增量状态
activate ump

ump -> r : 2.查询7种营销活动增量状态
note left
打包一口价
集点卡
第二件半价
满减送
加价购
赠品
限时折扣
end note
activate r
return 2.1返回

ump -> rij : 3.查询自定义会员价增量状态
note left
与其他7种营销活动存储数据结构不同，
因此需要单独处理
end note
activate rij
return 3.1返回

ump -> ump : 4.在增量状态集合中取最新更新时间
note left
1单店
2连锁：总部、合伙人、门店
由于可能存在 总部和合伙人都创建了营销活动
因此，需要取一个最后创建者
end note
activate ump
return 4.1返回

ump -> ump : 5.数据转换
activate ump
return 5.1返回
return 6返回

m -> ump : 7返回数据与自身数据比较，按需增量拉
activate ump

ump -> ump : 8查询数据
activate ump
return 8.1返回

return 9返回

@enduml