@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox
autoActivate on

'使用 toy 主题
!theme toy

'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 2.5

' 皮肤
skinparam sequence {
    LifeLineBackgroundColor #6FC8F2
    ParticipantBackgroundColor #6FC8F2
    ParticipantFontColor black
    ActorBackgroundColor #6FC8F2
    ActorFontColor black
}

actor 用户 as actor
participant StudentService as StudentService
participant StudentDomainService as StudentDomainService
participant ImageRecognitionService as ImageRecognitionService
database StudentRepository as StudentRepository
participant AugeGateway as AugeGateway
participant UicGateway as UicGateway

actor -> StudentService : 发起人工审核

StudentService -> StudentDomainService : 调用领域服务，发起自动审核

group Concurrent
    StudentDomainService -> ImageRecognitionService : 解析图片内容，通用文字识别
    return

    StudentDomainService -> ImageRecognitionService : 解析图片内容，手写体识别
    return
end group

StudentDomainService -> StudentDomainService : 匹配信息
note right of StudentDomainService
    姓名、学校、时间
end note
return
return

StudentService -> StudentDomainService : 调用自动审核通过领域服务
note right of StudentService
    奥格身份、用户标、库表状态
end note
StudentDomainService -> AugeGateway : 奥格身份
return
StudentDomainService -> UicGateway : 用户标
return
StudentDomainService -> StudentRepository : 库表状态修改
return
StudentDomainService -> StudentDomainService : 发出学生认证成功消息
return
return

return




@enduml