@startuml
'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox
autoActivate on

'使用 toy 主题
!theme toy

'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 2.5

' 皮肤
skinparam sequence {
    LifeLineBackgroundColor #6FC8F2
    ParticipantBackgroundColor #6FC8F2
    ParticipantFontColor black
    ActorBackgroundColor #6FC8F2
    ActorFontColor black
}

actor 用户 as actor
participant 宜搭 as yida
participant StudentService as StudentService
participant ImageRecognitionService as ImageRecognitionService
participant StudentAuthenticateDomainService as StudentAuthenticateDomainService
database StudentRepository as StudentRepository
participant AugeGateway as AugeGateway
participant UicGateway as UicGateway

actor -> yida : 进入审核页面
note right of actor
    高亮显示关键字，时间自动补全
end note
return

actor -> yida : 审核完成

yida -> StudentService : 审核回调

StudentService -> StudentAuthenticateDomainService : 人工审核完成
return

return 返回

return






@enduml