@startuml

'https://plantuml.com/sequence-diagram

'隐藏脚注
hide footbox

'使用 toy 主题
!theme toy

'自动激活
autoActivate on

'编号
autonumber 1

'隐藏孤立的参与者
hide unlinked

'文字对齐，向左对齐
skinparam sequenceMessageAlign left

'箭头粗度
skinparam sequenceArrowThickness 2

' 皮肤
skinparam sequence {
    LifeLineBackgroundColor #6FC8F2
    ParticipantBackgroundColor #6FC8F2
    ParticipantFontColor black
    ActorBackgroundColor #6FC8F2
    ActorFontColor black
}

actor 用户 as user
participant 前端 as front
participant 兑吧 as out
participant TKUserService as TKUserService
participant 阿里妈妈 as Alimama
database TUserTaskItemRepository as TUserTaskItemRepository

user -> front : 查看任务

front -> out : 查询商品

out -> TKUserService : 查询推荐商品，pageSize = topNum



group 置顶商品逻辑
    loop for i in 1..n
        TKUserService -> TUserTaskItemRepository : 查询过往浏览过的商品列表 list
        return lookedNum = ∑ list.size()
    end loop

    TKUserService -> Alimama : 查询，size = topNum + lookedNum
    return
    TKUserService -> TKUserService : 过滤商品列表
    note right of TKUserService
        以往浏览的商品，过滤
    end note

    return
    TKUserService -> TKUserService : 组装商品，商品打标
    note right of TKUserService
        今天浏览的商品，置灰
    end note
    return
end group

return
return
return

@enduml